name: update docs

on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'
      - '.github/workflows/update-docs.yml'
  pull_request:

env:
  DOKU_REPO: 'arrol/pages_smple'
  NODE_VERSION: '10.x'
  PYTHON_VERSION: '3.9'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Docu Repo
        uses: actions/checkout@v2
        with:
          repository: ${{ env.DOKU_REPO }}
          token: ${{ secrets.ACCESS_TOKEN }}
          ref: 'main'
          submodules: true
      - name: Checkout Submodules
        run: git submodule update --remote --recursive
      - name: Commit update
        uses: EndBug/add-and-commit@v7
          with:
            default_author: github_actions
            message: 'Auto updated submodule references'